### ISSUE TITLE
option for self-signed certs?

### ISSUE THREAD

**Issue by sre-ops** [rvojcik/gitlab-project-export#10]
As many people run gitlab on private instances, they may be using self-signed certs.  Is there a technique to work with this setup?

I'm thinking of a couple different solutions:
- an option to point to a cert file
- an option to disable SSL verification
- at least an update to README saying how to use REQUESTS_CA_BUNDLE to point to cert

**Comment by rvojcik** [comment]
Hi @sre-ops , 

It's good idea, i'll allocate some time to implement it. 

I'll add option for optional CA cert bundle and also for disable SSL verification. It can be helpful also for development and testing purposes.

**Comment by rvojcik** [comment]
@sre-ops I have added `gitlab.access.ssl_verify` option to configuration file. Check `config.yaml-example`

**Comment by sre-ops** [comment]
Awesome work, thank you!
