### ISSUE TITLE
API not respond well with 404

### ISSUE THREAD

**Issue by kukukk** [rvojcik/gitlab-project-export#14]
Hi,

I'm trying to use the script to export my Gitlab projects, but I get `API not respond well with 404` error.

I tried to specify my project as `group/project-name`, but I also tried with `/*`. Using `/*` it identifies all my projects and creates the folders for them (the whole group - project names hierarchy), but it gives the same 404 error for all projects.

In Gitlab I can access the project using `https://_gitlab_url/group/project-name`

I also tried to export the project from Postman. Using `https://_gitlab_url/api/v4/projects/2/export` works, but using `https://_gitlab_url/api/v4/projects/group%2Fproject-name/export` returns 404.

I'm using Gitlab 13.9.2-ce.0 (Dockerized).
I enabled all scopes for the Personal Access Token.

**Comment by rvojcik** [comment]
Hi @kukukk , Personal Access Token needs "only" API write permissions. So try to remove all others, because there is also API readonly scope. 

You need only API Write permissions for token

**Comment by kukukk** [comment]
I created a new Personal Access Token having only the `api` scope, but I have the same result.
Using `/*` for projects it manages to identify all my projects and create the folder structure for them, but not able to export them.

**Comment by kukukk** [comment]
Sorry, it was a mistake in my reverse proxy configuration. I had to add `AllowEncodedSlashes On` and `nocanon` to ProxyPass.

**Comment by rvojcik** [comment]
Thank you for letting me know. I was trying to simulate it on docker gitlab with no luck. Great to hear that you find the problem 👍😉
