### ISSUE TITLE
Option for exporting all projects

### ISSUE THREAD

**Issue by scottlinux** [rvojcik/gitlab-project-export#2]
Hi, I had to set [this value](https://github.com/rvojcik/gitlab-project-export/blob/master/lib/gitlab.py#L85) to `membership=False` in order to download all projects on a shared gitlab instance, with config of:

```
  projects: 
    - '/*'
```

I'm not sure if anyone knows of a better way to have this utility simply export all projects?

**Comment by rvojcik** [comment]
Hi thank you for this!

I will move membership option to config, to be able to set it from configuration file.
I tested it only on public gitlab.com so I had to use membership=False and forgot about private instances of gitlab.

Thanks
