### ISSUE TITLE
I have an error when exporting

### ISSUE THREAD

**Issue by VelTrenn** [rvojcik/gitlab-project-export#22]
python --version                                                                                                                                                                        fish-1 | 1 
Python 3.6.9

/gitlab-project-export.py -c ./config.yml                                                                                                                                              fish-1 | 0 [19:33:18]
Traceback (most recent call last):
  File "./gitlab-project-export.py", line 49, in <module>
    c = config.Config(args.config)
  File "/root/test/gitlab-project-export/gitlab_export/config.py", line 15, in __init__
    self.config_load()
  File "/root/test/gitlab-project-export/gitlab_export/config.py", line 43, in config_load
    self.config = yaml.load(self.conf_fh.read(), Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'

**Comment by rvojcik** [comment]
Hi @VelTrenn , 

thank you for your report. Can you get your version of pyyaml ?
You can have it installed from OS package, so check the version of the package, 
or it can be installed using pip3, then run pip3 list and look for PyYAML

If non of it worked try tu run python shel by running python3 
```
# python3
Python 3.6.9 (default, Nov 23 2019, 06:41:34) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> help(yaml)
```
There look for VERSION heading.

**Comment by VelTrenn** [comment]
when I installed via pip there were no errors
thank you very much
