### ISSUE TITLE
Abilty to import all projects withought having the list them

### ISSUE THREAD

**Issue by Panda911** [rvojcik/gitlab-project-export#24]
is there a way to have it import all projects from all users and groups. only way i figured out was listing out each user then using * behind it but just doing * or */* both error out

**Comment by rvojcik** [comment]
Hi Panda911, 

there is ability to export, but in import it's not only way to do that is for now create small list or shell oneliner which iterate over projects and import them as you wish in new location. 

There is also limitation that import doesn't create groups now. Maybe it's something we can add to it to help with importing projects to new gitlab instance.
