### ISSUE TITLE
error when importing

### ISSUE THREAD

**Issue by jgarijo1974** [rvojcik/gitlab-project-export#25]
Hi, I am trying to import a repo and I am getting :

API not respond well with 404 {"message":"404 Namespace Not Found"}
{"message":"404 Namespace Not Found"}
Import was not successful

this is the command I am running:

python3 gitlab_project_import/gitlab-project-import.py -c gitlab_project_import/config_import2.yml -f ./importedgitlab_cicdtar.gz "-p group/gitlab_cicd"

I did not find anywhere where I can specify a namespace. I used the same kind of config.yml as to export the repo. Do you have an example of a specific one for importing?

Thanks Javier

**Comment by rvojcik** [comment]
Hi @jgarijo1974 , 
in gitlab world namespace typicaly mean path to your group. So if your project is located in `somegroup/somesubgroup/myproject` it means namespace is `somegroup/somesubgroup` 

In your example group `/group` must be created before you run import. Import script doesn't create groups now, just projects.
